export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USERINFO: "SET_USERINFO",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_CURRENTPLAYING: "SET_CURRENTPLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
};
